apiVersion: v1
kind: Service
metadata:
  name: "{{ include "hawk.fullname" . }}-monitor"
  labels:
    {{- include "hawk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.monitor.service.type }}
  ports:
    - port: {{ .Values.monitor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ include "hawk.fullname" . }}-monitor"
