# Default values for hawk-envoy-plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hawkEnvoyPlugin:
  # The target namespace
  namespace: sock-shop
  
  # hawk service url
  hawkServiceApiUrl: "http://hawk-service.hawk.svc.cluster.local/api"

  # deploy httpbin for debugging
  httpbin: true



rabbitmq:
  auth:
    username: guest
    password: guest

# values for collector-go
collector:
  replicaCount: 1

  image:
    repository: ghcr.io/privacyengineering/collector-go
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main"

  service:
    type: ClusterIP
    port: 80
  
  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"


  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}


# values for consumer
consumer:
  replicaCount: 1

  image:
    repository: ghcr.io/privacyengineering/consumer
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main"

  service:
    type: ClusterIP
    port: 8080
  
  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""